play.http.secret.key = "changeme-in-production-use-env-var"
play.http.secret.key = ${?APPLICATION_SECRET}

pokeapi.base-url = "https://pokeapi.co"
pokeapi.base-url = ${?POKEAPI_BASE_URL}

play.filters.disabled += "play.filters.csrf.CSRFFilter"
